#!/usr/bin/env bash
set -e

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

nigiri stop --delete
nigiri start --liquid
sleep 20s
export TDEX_DAEMON_PATH=$(pwd)/test/datadir 
yarn clean
npx jest --detectOpenHandles test/e2e.spec.ts
yarn clean
npx jest --detectOpenHandles test/markets.spec.ts

popd