#!/usr/bin/env bash
set -e

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

nigiri stop --delete
nigiri start --liquid
sleep 15s
yarn clean
export TDEX_DAEMON_PATH=$(pwd)/test/datadir 
npx jest test --detectOpenHandles

popd